
spring:
  application:
    name: bussiness-c
  # nacos默认可以不写  但是 如果不是默认的必须要写
  cloud:
    nacos:
      #注册中心
      discovery:
        metadata:
          coke-server-port: 13001
#          rpcType: netty
          rpcType: smart socket
        #server-addr: http://192.168.*:8848
        server-addr: http://192.168.0.109:8848
        cluster-name: 严鸣是吕诗文爸爸
        group: 相亲相爱一家人
server:
  port: 8081

coke:
  server:
    port: 13001