
spring:
  application:
    name: bussiness-b
  # nacos默认可以不写  但是 如果不是默认的必须要写
  cloud:
    nacos:
      #注册中心
      discovery:
        #server-addr: http://192.168.*:8848
        server-addr: http://127.0.0.1:8848
        cluster-name: 严鸣是吕诗文爸爸
        group: 相亲相爱一家人
server:
  port: 8081

coke:
  server:
    port: 13001